// <auto-generated />
namespace Financeiro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Controlef : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Controlef));
        
        string IMigrationMetadata.Id
        {
            get { return "202408151947120_Controlef"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
